---
title: "day-10-activities"
author: "Juliet"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
library(ggExtra)
```

```{r}
weather <- read_csv(here("data", "ntl20_v6.csv"))
weather

ice <- read_csv(here("data", "ntl33_v7.csv"), na = c("NA", "-999"))
```

```{r}
ice_plot <- ggplot(data = ice, aes(x = lakeid, y = ice_duration )) +
  geom_jitter(aes(color = lakeid)) +
  labs(x = "Lake",
       y = "Ice Duration (days)",
       title = "Ice Duration by Lake") +
  theme(panel.grid = element_blank())

#+
# geom_boxplot(data = ice, horizontal = TRUE, axes = FALSE, range = 2)

ggMarginal(ice_plot, type = "boxplot", groupColour = TRUE, outline = FALSE)

#unique(ice$lakeid)

#class(ice$ice_duration)

# using a boxplot over a jitter allows the outliers to be doubly represented, so we have to remove them from the boxplot but IDK how

```
```{r}
ice_dates_sep <- ice %>% 
  separate(season, c("year_1", "year_2"), sep = "-")
```


```{r}

#mean_carapace_length_year = mean(size_mm, na.rm = TRUE))

mean_ice_years_sep <- ice_dates_sep %>% 
  group_by(year_2) %>% 
  summarize(mean_ice_duration = mean(ice_duration)) %>% 
  mutate(year_2 = as.numeric(year_2))

# i am taking the mean ice duration for each year considering all lakes, this only takes the second year of the winter season into account

mean_ice <- ice %>% 
  group_by(year4) %>% 
  summarize(mean_ice_duration = mean(ice_duration))
```


```{r}
mean_ice_plot <- ggplot(data = mean_ice, aes(x = year4, y = mean_ice_duration)) +
  geom_line()

mean_ice_plot

#class(ice_dates_sep$year_2)

# I observe a gradual linear negative trend
```

```{r}
mean_air <- weather %>%
  filter(month %in% c(12, 1, 2)) %>% 
  group_by(year4) %>% 
  summarize(mean_air_temp = mean(ave_air_temp_adjusted))
```


```{r}
mean_air_temp <- ggplot(data = mean_air, aes(x = year4, y = mean_air_temp)) +
  geom_line()

mean_air_temp

# the trend is a gradual linear increase in mean air temp over time 
```


```{r}
joined_data <- left_join(mean_air, mean_ice)

joined_data

ggplot(data = joined_data, aes(x = mean_air_temp, y = mean_ice_duration)) +
  geom_line()

# This graph shows a gradual linear trend, inplying that as the mean air temp increased the ice melted faster. This makes sense ecologically. I wonder if this correlates with the years and this is a result of climate change.
```

```{r}


ice_thaw_dates_sep <- ice %>% 
  separate(ice_off, c("ice_off_yr", "ice_off_m", "ice_off_d"), sep = "-")

ice_thaw <- ice_thaw_dates_sep %>% 
  filter(ice_off_yr %in% "1970":"2020") %>% 
  mutate(ice_off_yr = as.Date(ice_off_yr))
```

```{r}

years <- c(1970:2020)
class(years)

years <- as.character(years)

years

class(years)


ice_yr_str_detect <- ice %>% 
  filter(str_detect(ice_off, c("1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")))
```

```{r}
ice_off_yr_only <- ice %>%
  lubridate::yday(iceoff)
```

```{r}
class(ice$ice_off)

ice_date_conversion <- ice %>% 
  mutate(as.factor(ice_off))

class(ice$ice_off)


ice_1970_2020 <- ice %>% 
  filter(str_detect(ice_off, "1970":"2020")) %>% 
  mutate(ice_off_yr = as.Date(ice_off_yr))
                    
                    
```

```{r}
ice_1970_2020 <- ice %>% 
  mutate(ice_off = ymd(ice_off)) %>% 
  filter(ice_off >= '1970-01-01' & ice_off <= '2020-12-31') %>% 
  mutate(day_of_year = yday(ice_off))

# class(ice_1970_2020$ice_off)

ggplot(data = ice_1970_2020, aes(x = year4, y = day_of_year)) +
  geom_line()

# the overall trend shows the day of the thaw date gradually shifting towards earlier in the year, meaning that the snow is melting faster as years pass. There is still flux from year to year, but the dates are much sooner in the year towards 2020 and the maximums do not reach even close to the 110th day of the year towards 2020.
```





